server:
  port: 9500
spring:
  application:
    name: developer-register-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
          defaultZone: http://developer-register-server:9500/eureka/